### ISSUE TITLE
最新固件JPEG硬编码似乎不起作用

### ISSUE THREAD

**Issue by mcpanl** [sipeed/MaixPy#15]
最新固件JPEG硬编码似乎不起作用，使用文档示例的两种方式都不行，encode()后面没有执行，也没有输出。.h265文件大小也是0.

![图片](https://github.com/sipeed/MaixPy/assets/59745518/15fa33d6-b2ab-428c-b858-259f5b2f3398)

**Comment by lxowalle** [comment]
这是应该叫H265硬编码。然后这个问题我们已经发现，下个版本会修复

**Comment by Neutree** [comment]
已经更新，如果仍然有问题，请再打开issue
