### ISSUE TITLE
在没有屏幕的情况下，如何安装Runtime库呢？

### ISSUE THREAD

**Issue by mcpanl** [sipeed/MaixPy#21]
事情是这样的，我手里有一个带屏幕的Nano和不带屏幕的，不带屏幕的我先用串口调试登录、连WiFi。然后python中import maix始终报错，具体的错误都是跟xxxx.so有关。
```
>>> import maix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/maix/__init__.py", line 4, in <module>
    from ._maix.peripheral.key import add_default_listener
ImportError: Error loading shared library libmaixcam_lib.so: No such file or directory (needed by /usr/lib/python3.11/site-packages/maix/_maix.so)
```

后来实在不知道该怎么搞了，我就先把烧录好的卡插到带屏幕的Nano上，连网、安装Runtime后，再把卡拔下来，插到不带屏幕上的，自此就可以正常import maix了。不知道是我没找到文档，还是文档没有写如何用命令行安装Runtime。

**Comment by Neutree** [comment]
licheervnano 不支持maixpy的，只有maixcam支持，没有屏幕的maixcam目前没什么好的方法，官方都还没买不带屏幕的套餐呢，之后会优化不带屏幕的体验。
