### ISSUE TITLE
RunTimeError : Value is null and camera suddenly shutdown while using yolov8n 

### ISSUE THREAD

**Issue by Diqtra** [sipeed/MaixPy#22]
![Screenshot 2024-06-23 151912](https://github.com/sipeed/MaixPy/assets/162720838/9e1099f3-60be-4987-9d18-9862b6e3bce4)
My Maixcam has an error when using yolov8n, and the message says, "RuntimeError: Value is Null: Camera read failed." I'm using the yolov8n that comes with MaixPy. The camera works but only for a little while before stopping.

**Comment by lxowalle** [comment]
Hi, from the logs it looks like you're launching multiple apps, please make sure that the MaixVision app and the MaixCAM app aren't launching at the same time (MaixCAM black screen means no apps are running) . If that doesn't solve the problem, you can try to get the latest image from release, update it and try again!

**Comment by JimlyAdam** [comment]
It also happened to me, Maixvision app was just for knowing the log file, the fact is the program  was installed and then exit with code 1... This happened even with the latest MaixPy suddenly exit by itself but sometimes it doesn't...

![IMG20240626104731~3.jpg](https://github.com/sipeed/MaixPy/assets/121883815/6c4146bf-70e6-4bd6-af97-de3aef587ec4)

**Comment by lxowalle** [comment]
This may not be a software problem, but the camera is not connected properly, you can open the back cover to check if the camera cable is loose.

**Comment by JimlyAdam** [comment]
Unfortunately, I have two MaixCAM, but it happened at both, I've tried to replace the MicroSD and check all the flexible but those was safe

**Comment by lxowalle** [comment]
I still haven't reproduced your problem, can you try the old mirror first?
