### ISSUE TITLE
How to know the true difference between them? 

### ISSUE THREAD

**Issue by DinalRok** [sipeed/MaixPy#25]
Hi, I am very interested in MaixCAM. I learned from the documentation that MaixCAM is based on the LiecheeRV Nano core development board, and I also received a warning that MaixCAM can use the materials of LicheeRV Nano and SG2002, but LicheeRV-Nano and other SG2002 chip products cannot use software such as MaixPy MaixCDK MaixVision, please do not buy the wrong one to waste time and money.”， I want to know, why can't we explain the reason in detail, but directly deny it?

![MaixCAM](https://github.com/sipeed/MaixPy/assets/174095840/8b3a9881-622b-47f4-aa25-77b785e4904f)

![Nano](https://github.com/sipeed/MaixPy/assets/174095840/6fe4d827-2cac-4c25-b391-3f4d95403b42)

Is it only for profit purposes, as cameras and touchscreens can now be easily purchased from Amazon? Prevent users from purchasing loose parts and assembling them into MaixCAM? I hope it can be clearly stated whether there is a difference in hardware between them, or whether certain information is written into the chip when it leaves the factory to distinguish whether it is an official MaixCAM kit purchased or a self assembled kit? Although it is difficult for you to admit the truth.

**Comment by Neutree** [comment]
it is not difficult for us to admit the truth........ just u can't understand what the words means....

MaixCAM provide MaixPy and MaixCDK but licheeRVNano not support, that's it, you can understand the price is for the software license, and only maixcam have license when production, we marked hardware info when production.
