### ISSUE TITLE
 根据文档，执行update_img.sh时报错

### ISSUE THREAD

**Issue by mcpanl** [sipeed/MaixPy#26]
[https://wiki.sipeed.com/maixpy/doc/zh/pro/compile_os.html](https://wiki.sipeed.com/maixpy/doc/zh/pro/compile_os.html)

根据上述文档，执行update_img.sh时报错

![图片](https://github.com/sipeed/MaixPy/assets/59745518/60cee9d4-8004-4cfb-972b-1df757026421)

如果我用apt-get安装fuse2fs并修改脚本

![图片](https://github.com/sipeed/MaixPy/assets/59745518/efad9eba-6fef-46e3-a85a-3c42aad9d02a)

它仍然报错

![图片](https://github.com/sipeed/MaixPy/assets/59745518/cbb73a8e-b4be-4dc0-8519-6e8c1f01a6a2)

如果按照提示执行这个命令仍然报错

![图片](https://github.com/sipeed/MaixPy/assets/59745518/094b5d99-f362-4280-93f7-0622d51fb72d)

**Comment by Neutree** [comment]
![image](https://github.com/sipeed/MaixPy/assets/8625829/0eef84b6-df1b-4bf1-aa5c-55642512c441)

**Comment by Neutree** [comment]
https://github.com/sipeed/LicheeRV-Nano-Build/tree/main/host

**Comment by mcpanl** [comment]
我知道了，可能我拉取仓库的时候没拉去完整，我再试一下哈，谢谢！

**Comment by Neutree** [comment]
ci 已经构建过了，如果还有问题 可以参考CI的构建脚本
