### ISSUE TITLE
不存在image.send_to_maixvision() 

### ISSUE THREAD

**Issue by Jerry1962325** [sipeed/MaixPy#27]
我遵循教程，但是发现 send_to_maixvision() 方法不存在，如下两图所示：（正确的图片效果来自我的修复）
![image](https://github.com/sipeed/MaixPy/assets/60921621/cba5011b-a901-4fc6-9fd1-c79a456153b0)
![image](https://github.com/sipeed/MaixPy/assets/60921621/aa845973-a1bb-4b8d-a371-6e37e2bae9a3)
这或许有用，但是和教程的精神不符：
```Python
from maix import image, display

img = image.Image(320, 240)
disp = display.Display()

img.draw_rect(0, 0, img.width(), img.height(), color=image.Color.from_rgb(255, 0, 0), thickness=-1)
img.draw_rect(10, 10, 100, 100, color=image.Color.from_rgb(255, 0, 0))
img.draw_string(10, 10, "Hello MaixPy!", color=image.Color.from_rgb(255, 255, 255))
while 1:
    disp.show(img)
```

**Comment by Neutree** [comment]
噢 文档写错了， 是 `maix.display.send_to_maixvision(img)` 欢迎 PR 修改文档

**Comment by Jerry1962325** [comment]
那4.3.2版本的“Fix Bugs”日志也错了2333
