### ISSUE TITLE
MaixCAM支持网口吗？

### ISSUE THREAD

**Issue by Meekdai** [sipeed/MaixPy#33]
我想通过网口把视频和图片传输到电脑上？我看到LicheeRV-Nano是有适配的网口的，不知道MaixCAM能否支持？

**Comment by Neutree** [comment]
可以的，只是默认的没有焊接网口

**Comment by Meekdai** [comment]
> 注意：MaixCAM 可以使用 LicheeRV-Nano 和 SG2002 的资料， 反之 LicheeRV-Nano 和其它 SG2002 芯片产品没法使用 MaixPy MaixCDK MaixVision 等软件，请不要购买错误浪费时间和金钱。
如果你希望快速上手开发应用，请选择 MaixCAM, 如果你是资深 Linux 开发者，只想基于 SG2002 原厂资料开发，可以选择 LicheeRV-Nano。

谢谢，我看到你们文档中有这个描述，是因为MaixCAM和LicheeRV-Nano的原理图不一样吗？

因为我不需要屏幕，目前MaixCAM Lite版本好像没有货，而LicheeRV-Nano-E[网口版]又是有货的，所以比较好奇为什么LicheeRV-Nano不能使用MaixPy。

**Comment by Neutree** [comment]
主要是软件区别，硬件其实是一样的，因为rn nano卖得实在太便宜了，所以要用 MaixPy 相当于是多了一个license费用，你也可以找客服加50块给rvnano 买一个license 就能用maixpy了

**Comment by Meekdai** [comment]
了解了，多谢。
