### ISSUE TITLE
有延迟很低的视频传输应用吗？

### ISSUE THREAD

**Issue by Meekdai** [sipeed/MaixPy#36]
最近买了MaixCAM，简单测试了一些视频传输的例子，但是目前没有找到延迟低的应用。示例里面的rtsp这些延迟都在1秒左右。

也测试了下面的代码，延迟稍微低了点，但是如果分辨率调高的话，延迟也会增加。
https://github.com/sipeed/MaixPy/blob/main/examples/vision/streaming/http_stream.py

我之前在V3S上面跑的[mjpeg-streamer](https://sourceforge.net/projects/mjpg-streamer/)，延迟非常低，几乎感觉不到。想请问一下是否有大神移植过mjpeg-streamer到MaixCAM上？如果没有的话，是否有一些移植的指导文件，可供参考？

谢谢

**Comment by Neutree** [comment]
用RTSP就行了，在接收端把延迟（缓冲）设置小一点，比如 VLC 就有缓存设置
![image](https://github.com/user-attachments/assets/5c7440b8-25a2-4b21-87da-18ce613dda63)

**Comment by Meekdai** [comment]
@Neutree 谢谢，我尝试了最小可设置为100ms，接收1080P的流没有问题。还是能感觉到有延迟的，不过比之前好很多了。
