### ISSUE TITLE
希望可以添加BLE低功耗蓝牙例程，方便使用蓝牙配网

### ISSUE THREAD

**Issue by mcpanl** [sipeed/MaixPy#41]
希望可以添加BLE低功耗蓝牙例程，方便使用蓝牙配网，谢谢！

**Comment by Neutree** [comment]
板子默认蓝牙没有使能，需要焊接几个电阻，即默认是不可用的，所以蓝牙不提供例程，有能人欢迎PR

**Comment by mcpanl** [comment]
能否给个AIC8800D的资料呢，方便贴上0402*4排阻后自己开发蓝牙功能

**Comment by Neutree** [comment]
linux通用方法，驱动系统应该已经有了，按照linux标准方法启用蓝牙就好了，你有兴趣可以试试

**Comment by Neutree** [comment]
这个问题我还是保持打开，欢迎提交文档或者代码PR

**Comment by Neutree** [comment]
参考：
* https://maixhub.com/share/62
* https://maixhub.com/share/58
