### ISSUE TITLE
ModuleNotFoundError: No module named 'Maix'

### ISSUE THREAD

**Issue by nguyenvulong** [sipeed/MaixPy#44]
I found this documentation:[ https://wiki.sipeed.com/soft/maixpy/en/develop_kit_board/module_microphone.html]( https://wiki.sipeed.com/soft/maixpy/en/develop_kit_board/module_microphone.html)
but it seems like there's no implementation of this module

is it only available in the older version of `MaixPy`?

This is really confusing because [https://wiki.sipeed.com/soft/maixpy/en/index.html](https://wiki.sipeed.com/soft/maixpy/en/index.html) is actually `MaixPy-V1`, not `MaixPy`.

```python
>>> from Maix import MIC_ARRAY as mic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Maix'
>>> from maix import MIC_ARRAY as mic
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'MIC_ARRAY' from 'maix' (/home/lvnguyen/.pyenv/versions/sound-augmentation/lib/python3.9/site-packages/maix/__init__.py)
```

**Comment by Neutree** [comment]
this repo is MaixPy v4, not fully compatible with the maixpy v1, the compatible API is here: https://github.com/sipeed/MaixPy/tree/main/maix/v1

**Comment by Neutree** [comment]
and all maixpy v4's doc under  https://wiki.sipeed.com/maixpy/   not  https://wiki.sipeed.com/soft/

**Comment by nguyenvulong** [comment]
> this repo is MaixPy v4, not fully compatible with the maixpy v1, the compatible API is here: https://github.com/sipeed/MaixPy/tree/main/maix/v1

I believe that it's not implemented there but a placeholder only
See the screenshot, all methods are `pass`ed
 
![image](https://github.com/user-attachments/assets/049d5c94-ed31-4c66-acc9-e1f03077bcf5)

It should be here [https://github.com/sipeed/MaixPy-v1](https://github.com/sipeed/MaixPy-v1)
By the way, if you have the installation documentation, please provide. Thank you!

**Comment by Neutree** [comment]
what's your board? MaixCAM or k210, if K210 just use MaixPy v1, if MaixCAM please refer to https://wiki.sipeed.com/maixpy/doc/en/audio/play.html, and MaixCAM not support the  MIC array cause MaixCAM's I2S not suuport yet

**Comment by nguyenvulong** [comment]
I am considering both K210 and MaixCAM
Does `MaixCAM` support [MaixPy-v1](https://github.com/sipeed/MaixPy-v1)?

Thanks.

**Comment by Neutree** [comment]
MaixCAM not support MaixPy-v1，but MaixPy v4 contain maybe 95% + MaixPy v1's function and have more ability, if you use vision functions please use MaixCAM.

**Comment by nguyenvulong** [comment]
I want to use Audio (for example, sound localization).
I guess I will choose K210 for now.

Good day Neutree!
