### ISSUE TITLE
MaixBit K210 语音识别器未找到

### ISSUE THREAD

**Issue by Rhythm8503** [sipeed/MaixPy#46]
你好！

我的翻译可能不是很好，但我正在尝试使用语音识别器进行孤立的单词识别。然而，MaixPy 说当我在地址 0x500000 处刻录它时找不到它。请帮忙！

**Comment by Neutree** [comment]
this repo is for MaixPy v4, k210 please visit MaixPy-v1 repo, and please read k210's doc
