### ISSUE TITLE
支持audio.Player()的音量调节功能

### ISSUE THREAD

**Issue by mcpanl** [sipeed/MaixPy#51]
目前文档中似乎不支持Player的volume()方法调节音量，希望大佬能支持一下audio.Player()的音量调节功能，感谢！

**Comment by lxowalle** [comment]
驱动暂时不支持设置播放的音量，可以尝试在电脑上把要播放的音频文件音量放大后再给Player播放

**Comment by avatarlinken** [comment]
> 驱动暂时不支持设置播放的音量，可以尝试在电脑上把要播放的音频文件音量放大后再给Player播放

后面会有音量调节接口释放出来吗？C的API有调节音量接口吗？

**Comment by Neutree** [comment]
录音和播放均添加了`volume()`函数，以及系统设置APP也添加了对应选项，更新到>= 4.9.0即可
