### ISSUE TITLE
nn.Speech关键词识别，如何自己训练唤醒词呢，是否有文档可以参考

### ISSUE THREAD

**Issue by mcpanl** [sipeed/MaixPy#53]
nn.Speech关键词识别，如何自己训练唤醒词呢，是否有文档可以参考。目前示例模型中包含了三个关键词。
![图片](https://github.com/user-attachments/assets/c8bcb514-f256-436a-8290-97212996d121)

**Comment by Neutree** [comment]
直接修改列表里面的拼音就好了，后面文档补充一下
