### ISSUE TITLE
请问如何复用板载麦克风呢，一边录音，一边进行关键词识别。

### ISSUE THREAD

**Issue by mcpanl** [sipeed/MaixPy#54]
请问如何复用板载麦克风呢，一边录音，一边进行关键词识别。目前测试了一下只能初始化其中一个，如果尝试初始化另一个功能的话，就会报错。

**Comment by 916BGAI** [comment]
目前无法同时进行录音和关键词识别，只能进行其中一个。可以先保存录制的pcm或者wav音频，然后再导入音频文件进行识别。
