### ISSUE TITLE
nn.PP_OCR recognize疑问

### ISSUE THREAD

**Issue by rsj123** [sipeed/MaixPy#56]
在文档中提到：
> 如果你已经有处理好了的文字图，即一张图中已知文字的四个角坐标，可以不调用detect函数，二是只调用recognize函数，这样就不会检测而是仅仅识别图片中的文字  

但是在api文档：https://wiki.sipeed.com/maixpy/api/maix/nn.html#PP_OCR
以及源码中均未找到`recognize`函数，同时在最新的release 4.7.2中执行以下代码时也提示不存在recognize方法
``` python
rec = ocr.recognize(obj_img)
```

> Traceback (most recent call last):
>   File "/tmp/maixpy_run/main.py", line 18, in <module>
>     rec = ocr.recognize(obj_img)
>           ^^^^^^^^^^^^^
> AttributeError: 'maix._maix.nn.PP_OCR' object has no attribute 'recognize'

**Comment by Neutree** [comment]
确实没有，忘记加API了，已经加了 https://github.com/sipeed/MaixCDK/commit/904385c4cca995685f5a0be94ba238bad65b5fc3 ， 下个release版本就有了
