### ISSUE TITLE
哪个API 可以滑动屏幕，显示更多信息呢？

### ISSUE THREAD

**Issue by lfpu** [sipeed/MaixPy#57]
有没有一个api 可以像滑动， maixCAM 主页一样，滑动显示内容

**Comment by Neutree** [comment]
那个是UI框架实现的，用C+ LVGL 写的，python想要实现比较麻烦，不过也可以实现，就是不停检测坐标画动画，你可以思考一下

**Comment by lfpu** [comment]
> 那个是UI框架实现的，用C+ LVGL 写的，python想要实现比较麻烦，不过也可以实现，就是不停检测坐标画动画，你可以思考一下

好吧，我以为是他有封装好的API。 多谢

**Comment by Neutree** [comment]
目前还没有合适的给python用的ui框架
