### ISSUE TITLE
自己造好的whl轮子为什么说该平台不支持？

### ISSUE THREAD

**Issue by lfpu** [sipeed/MaixPy#58]
import os

os.system('pip install /root/Mywhl/Myexample-1.0-cp311-cp311-win_amd64.whl')

print("done")

下面是报错：

ERROR: Myexample-1.0-cp311-cp311-win_amd64.whl is not a supported wheel on this platform.
WARNING: There was an error checking the latest version of pip.
done

program exited

**Comment by lfpu** [comment]
是否是 setup.py 的参数配置问题吗？

下面是setup.py
from setuptools import setup, Extension
 
module = Extension('Myexample', #python module name
                   sources=['Myexample_module.cpp'],
                   extra_compile_args=['-std=c++11'])

setup(name='Myexample', #python module name
      version='1.0',
      author='lfpu',
      author_email='pulongfei@outlook.com',
      description='Example package with C++ extension',
      long_description=open('README.md').read(),
      long_description_content_type='text/markdown',
      url='https://github.com/lfpu',
      classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
      ],
      ext_modules=[module]
)

**Comment by lfpu** [comment]
按照[编译 MaixPy 源码](https://wiki.sipeed.com/maixpy/doc/zh/source_code/build.html) 步骤编译轮子报错，详情看下图

![image](https://github.com/user-attachments/assets/d2f4fc60-0818-4d5f-847b-79847a6269c7)

**Comment by Neutree** [comment]
Myexample-1.0-cp311-cp311-win_amd64.whl  你读一读文件名， win_amd64 即给 windows x86 编译的，你拿到maixcam 的 risc-v 能运行就怪了。

用 `python setup.py bdist_wheel maixcam` 命令

**Comment by lfpu** [comment]
> Myexample-1.0-cp311-cp311-win_amd64.whl 你读一读文件名， win_amd64 即给 windows x86 编译的，你拿到maixcam 的 risc-v 能运行就怪了。
> 
> 用 `python setup.py bdist_wheel maixcam` 命令

噢噢噢噢，多谢
