### ISSUE TITLE
最新code编译到最后link报错

### ISSUE THREAD

**Issue by 13760209346** [sipeed/MaixPy#6]
最新code，编译到最后报错link的错误

home/dragon/Desktop/dragon/MaixCDK/dl/extracted/toolchains/maixcam/host-tools/gcc/riscv64-linux-musl-x86_64/bin/../lib/gcc/riscv64-unknown-linux-musl/10.2.0/../../../../riscv64-unknown-linux-musl/bin/ld: maix/libmaix.so: undefined reference to `mmf_try_deinit(bool)'
/home/dragon/Desktop/dragon/MaixCDK/dl/extracted/toolchains/maixcam/host-tools/gcc/riscv64-linux-musl-x86_64/bin/../lib/gcc/riscv64-unknown-linux-musl/10.2.0/../../../../riscv64-unknown-linux-musl/bin/ld: maix/libmaix.so: undefined reference to `mmf_set_again(int, unsigned int)'
/home/dragon/Desktop/dragon/MaixCDK/dl/extracted/toolchains/maixcam/host-tools/gcc/riscv64-linux-musl-x86_64/bin/../lib/gcc/riscv64-unknown-linux-musl/10.2.0/../../../../riscv64-unknown-linux-musl/bin/ld: maix/libmaix.so: undefined reference to `mmf_get_luma(int, unsigned int*)'
/home/dragon/Desktop/dragon/MaixCDK/dl/extracted/toolchains/maixcam/host-tools/gcc/riscv64-linux-musl-x86_64/bin/../lib/gcc/riscv64-unknown-linux-musl/10.2.0/../../../../riscv64-unknown-linux-musl/bin/ld: maix/libmaix.so: undefined reference to `mmf_get_again(int, unsigned int*)'
/home/dragon/Desktop/dragon/MaixCDK/dl/extracted/toolchains/maixcam/host-tools/gcc/riscv64-linux-musl-x86_64/bin/../lib/gcc/riscv64-unknown-linux-musl/10.2.0/../../../../riscv64-unknown-linux-musl/bin/ld: maix/libmaix.so: undefined reference to `mmf_get_vi_vflip(int, bool*)'
/home/dragon/Desktop/dragon/MaixCDK/dl/extracted/toolchains/maixcam/host-tools/gcc/riscv64-linux-musl-x86_64/bin/../lib/gcc/riscv64-unknown-linux-musl/10.2.0/../../../../riscv64-unknown-linux-musl/bin/ld: maix/libmaix.so: undefined reference to `mmf_get_saturation(int, unsigned int*)'
/home/dragon/Desktop/dragon/MaixCDK/dl/extracted/toolchains/maixcam/host-tools/gcc/riscv64-linux-musl-x86_64/bin/../lib/gcc/riscv64-unknown-linux-musl/10.2.0/../../../../riscv64-unknown-linux-musl/bin/ld: maix/libmaix.so: undefined reference to `mmf_get_constrast(int, unsigned int*)'
/home/dragon/Desktop/dragon/MaixCDK/dl/extracted/toolchains/maixcam/host-tools/gcc/riscv64-linux-musl-x86_64/bin/../lib/gcc/riscv64-unknown-linux-musl/10.2.0/../../../../riscv64-unknown-linux-musl/bin/ld: maix/libmaix.so: undefined reference to `mmf_get_vi_hmirror(int, bool*)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/MaixPy.dir/build.make:115: MaixPy] Error 1
make[1]: *** [CMakeFiles/Makefile2:729: CMakeFiles/MaixPy.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by Neutree** [comment]
这个是maixcdk的提交问题，后面我们弄一个stable分支
