### ISSUE TITLE
MaixCAM最新镜像中的maix.sys模块指向的是python自带的sys模块

### ISSUE THREAD

**Issue by ElluIFX** [sipeed/MaixPy#7]
如题，测试如下：

![image](https://github.com/sipeed/MaixPy/assets/31679332/d543933d-4a80-46a6-a3c5-da7f7b2f6b0d)

应该是`__init__.py`中在添加模块时导入`sys`导致的冲突

考虑到python自带的`sys`使用频率极高，且MaixPy的example基本使用的是`from maix import xxx`的导入方式，更加剧了冲突的发生，个人建议是这个模块或许应该改名以规避一些潜在问题

**Comment by Neutree** [comment]
已经解决了，手动更新一下 MaixPy 到 4.1.0，或者等下一个镜像更新，新镜像在今天或者明天更新
