### ISSUE TITLE
编译系统后开机发现不显示DeviceKey 求指点一下可能出问题的地方

### ISSUE THREAD

**Issue by mcpanl** [sipeed/MaixPy#79]
1. 克隆LicheeRV-Nano-Build仓库，并模仿 /.github/workflows/licheervnano-host-linux-amd64.yml 的各个步骤，一步一步进行操作，中途没有任何报错，成功编译出了img文件。编译后将这个img文件复制到了`~/maix/os/`目录中备用。
![图片](https://github.com/user-attachments/assets/7d381ff0-ec75-48b0-ab09-41870e4f82bf)
2. 克隆MaixCDK和MaixPy仓库，同样按照教程先把必要的环境安装好，python用的3.11系统是ubuntu22.04。
3. 模仿/.github/workflows /release_maixcam.yml的各个步骤，一步一步操作，中途也没有报错，最后一条执行的命令是
```
./gen_os.sh ~/maix/os/2024-11-27-01-27-441888.img ../../dist/MaixPy-4.7.8-py3-none-any.whl tmp/dl_builtin_files/sys_builtin_files
```
中途没有报错，成功生成`tmp/maixcam-2024-11-27-maixpy-v4.7.8.img.xz`文件。
![图片](https://github.com/user-attachments/assets/bdb68998-a489-4bcb-b64e-a43832170c97)
4. 先使用SD Card Format将卡格式化，然后将`tmp/maixcam-2024-11-27-maixpy-v4.7.8.img.xz`复制出来进行烧录，烧录成功上电开机，屏幕正常点亮，WiFi、摄像头扫码都正常，但是设备信息里面没有显示DeviceKey，而且储存空间只显示了1G左右，导致这个的原因有可能是哪些呢，求指导或者指点一下，然后我再进行修改或者尝试，谢谢！

![d00987760c69dd5bee18c3b0d2fce5ca](https://github.com/user-attachments/assets/fe79c558-4fe9-417f-9cc4-df3c1f8fd611)
![36112f82aa70c0f19e05d55ad8a350d0](https://github.com/user-attachments/assets/6500df32-61fc-4e7d-b75a-fa7644f9d7bf)
![a1eafb583f7b70d3b5ae04d1e59bcd00](https://github.com/user-attachments/assets/1ea41d91-6a28-4ec5-a193-4b98624888ea)

**Comment by Neutree** [comment]
最后发现是 licheerv build 系统源码问题，已经修复了

**Comment by mcpanl** [comment]
感谢！
