### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 1716775457damn** [sipeed/MaixPy#8]
原本程序正常运行，但是我修改了颜色阈值后点错了，直接将文件烧到闪存里了，然后k210就不发数据了
![image](https://github.com/sipeed/MaixPy/assets/162271420/0a60dd42-c59d-45f5-abb9-7764b464e337)

**Comment by Neutree** [comment]
K210 问题请到 maixpy_v1 仓库，你这个问题重新上电连接应该就可以了，再不行就重新烧录固件
