### ISSUE TITLE
还是会报错，代码封装到不同py

### ISSUE THREAD

**Issue by lfpu** [sipeed/MaixPy#86]
可以的，maixvision 打开文件夹，然后在文件夹里面放py, import 就行，更新Maixvision到 v1.2.0 代码就不会报错了

_Originally posted by @Neutree in https://github.com/sipeed/MaixPy/issues/85#issuecomment-2516344818_

**Comment by lfpu** [comment]
![image](https://github.com/user-attachments/assets/99448553-24c2-4c71-a61e-a35bf919b569)



![image](https://github.com/user-attachments/assets/a5109fd6-11a2-446c-bf53-67af54fbac13)


![image](https://github.com/user-attachments/assets/8316e2ef-5ee3-4a33-8f03-d34dad9eb37e)

**Comment by Neutree** [comment]
一个问题没必要开两个issue，关掉了还可以再打开的。

测了一下，第一次打开应该是正常的，或者先把所有文件关闭，再打开文件夹也是可以的。
是一个bug，下个版本修复。可以暂时用上面的两种方法临时解决

**Comment by lfpu** [comment]
我是无论如何都不行，不过没关系，期待下个版本解决

**Comment by Neutree** [comment]
最简单的方法，重启，打开文件夹就可以
