### ISSUE TITLE
ImportError: Error loading shared library libpostproc.so.55: No such file or directory

### ISSUE THREAD

**Issue by pauceano** [sipeed/MaixPy#87]
Using Maxivision with a maxicam.
Trying to run the examples, I get this error: ImportError: Error loading shared library libpostproc.so.55: No such file or directory
I have installed ffmpeg for python, but I do not know how to install libraries and this library is not there.

**Comment by Neutree** [comment]
we only ensure MaixPy run on MaixCAM, other platform we don't matain

**Comment by pauceano** [comment]
I am using MaixCAM with Maixvision, following the manuals. Actually I am just trying the examples now.

**Comment by Neutree** [comment]
Please burn latest **system**(.xz file) first https://github.com/sipeed/MaixPy/releases/tag/v4.8.2

**Comment by pauceano** [comment]
Thank you very much, last version solved it.
