### ISSUE TITLE
如何把Flask(__name__) 消亡。

### ISSUE THREAD

**Issue by lfpu** [sipeed/MaixPy#89]
web = Flask(__name__)  这个如何消亡呢？  而且flask 这个没有说明文档

**Comment by Neutree** [comment]
please use English, your Chinese translation is bad, we can't understand

**Comment by lfpu** [comment]
how to dispose this object Flask(__name__), and there was no documentation for Flask

**Comment by Neutree** [comment]
documentation here: https://flask.palletsprojects.com/en/stable/
