### ISSUE TITLE
MaixPy 4.2.0: Wifi Setup without runtime not possible ..

### ISSUE THREAD

**Issue by bkircher67** [sipeed/MaixPy#9]
… but runtime installation requires Wifi. I‘m confused.

![IMG_0444](https://github.com/sipeed/MaixPy/assets/586166/8ae47d18-ceff-42e2-9b69-2254dae3d935)

**Comment by Neutree** [comment]
maybe its a bug, just use the old version, we will fix it netx monday....

if you want to use this image, just connect it by maixvision and edit the `/boot/wifi.ssid` and `wifi.pass` file, and reboot ( it's better to soft reboot by execute `os.system("reboot")`, when bootup, the wifi will automatically connect to your AP

**Comment by bkircher67** [comment]
Thanks! I already fixed it with an uart-ssh session and using the wpa_supplicant app to connect via wifi. Then I could install the runtime. But I assume your solution is faster and more elegant …

**Comment by Neutree** [comment]
I fiexed it, just try: https://github.com/sipeed/MaixPy/releases
