### ISSUE TITLE
Bluetooth -  any plans to add support?

### ISSUE THREAD

**Issue by hellvesper** [sipeed/MaixPy#91]
I saw that wireless module on MaixCAM support bluetooth but it disconnect, you should solder 4 jumpers to connect (https://wiki.sipeed.com/hardware/en/lichee/RV_Nano/2_unbox.html).

![bt jumpers](https://wiki.sipeed.com/hardware/en/lichee/assets/RV_Nano/unbox/BLE_RES.jpg)

But it would be nice to see support BT in high level api like MaixCDK and MaixPy. 

Also would be nice to have very handy `btstack` (https://github.com/bluekitchen/btstack) ported, which will open access to libs like `bluepad32` to connect gamepads, and communicate with BLE devices and smartphones, it so much better than linux standard bluez

**Comment by Neutree** [comment]
system already have BT driver, you can have a try。
here are two blog shared by community, use translation tool by brower to view:
* hardware: https://maixhub.com/share/58
* software: https://maixhub.com/share/62

**Comment by hellvesper** [comment]
> system already have BT driver, you can have a try。 here are two blog shared by community, use translation tool by brower to view:
> 
> * hardware: https://maixhub.com/share/58
> * software: https://maixhub.com/share/62

This is helpful, thank you!
